---
- name: Check if secrets.yml exists in platform
  ansible.builtin.stat:
    path: "{{ inventory_dir }}/secrets.yml"
  register: _secrets_file
  delegate_to: localhost
  become: false

- name: Include secrets
  ansible.builtin.include_vars: "{{ inventory_dir }}/secrets.yml"
  when: _secrets_file.stat.exists
